### ISSUE TITLE
Review Problem Statement (CAS 741)

### ISSUE THREAD

**Issue by shmouses** [shmouses/SPDFEM#1]
Dear Dr. Smith 
Please review the uploaded document. 
Regards,

**Comment by smiths** [comment]
Good start @shmouses.

I have the following comments:

- the problem statement is a simple document, you don't need a table of contents :smile:
- clarify the scope of your work - as written, this seems too big for 741.  What libraries will you likely be using to provide parts of the implementation?  What part will be done in 741, and what part will be for future work?
- Use the provided `.gitignore` file
- The issue should include a link the file to be reviewed, or the commit hash where the latest version is found

In addition to the above, please go through the problem statement checklist at:

https://gitlab.cas.mcmaster.ca/smiths/cas741/-/blob/master/BlankProjectTemplate/docs/ProblemStatement/ProbState-Checklist.pdf

Once the above has been dealt with, I will approve your problem statement.

**Comment by shmouses** [comment]
Dear Dr. Smith (@smiths),

The revised ProblemStatement.tex is available at:
[https://github.com/shmouses/SPDFM/blob/master/docs/ProblemStatement/ProblemStatement.tex](url)

and ProblemStatement.pdf at:
[https://github.com/shmouses/SPDFM/blob/master/docs/ProblemStatement/ProblemStatement.pdf](url)

The Diff.pdf tracks the changes which can be found at:
[https://github.com/shmouses/SPDFM/blob/master/docs/ProblemStatement/Diff.pdf](url)

and the Diff.tex at: 
[https://github.com/shmouses/SPDFM/blob/master/docs/ProblemStatement/Diff.tex](url)

Your consideration is appreciated in advance.


Regards,
Shayan

**Comment by smiths** [comment]
Thank you @shmouses.  Rather than creating your own diffs, you can just use the features of GitHub.  If you include the commit hash where the changes are made, there will a link to the commit.  For instance, a link like the following is a convenient way to see the changes:

f864e043ada7290aa8f83b223162aad8d72e4503

Since there aren't any comments, you can delete the comments from your file.  That is, you can remove `\an{comment}`.

Since there is existing work that you will be building upon, I believe that this project is feasible within the scope of 741.  I'll approve your project.  :smile:.
