### ISSUE TITLE
NFR 3

### ISSUE THREAD

**Issue by muralidn** [shmouses/SPDFEM#12]
@shmouses 

![image](https://user-images.githubusercontent.com/71282513/95972138-b94cc500-0e2f-11eb-8900-2345b96ef772.png)

The allowed exportable format is specific to your application. Therefore, I believe it is a functionality of your application, and is a functional requirement. Additionally stating  "whatever desirable format" is probably not the right wording.

**Comment by shmouses** [comment]
As it does not directly link to an IM it cannot be a functional requirement, it is an NR I believe. The wording can be improved.

**Comment by muralidn** [comment]
@shmouses 
Thanks for the response.

According to the paper, A New Requirements Template for Scientific Computing - Spencer Smitha and Lei Laia, Non-functional requirements are requirements that affect an application as a whole, like quality, security, performance, etc.

Therefore I am not sure if this requirement would come under that category. Dr. @smiths could you please share your thoughts on this?.

**Comment by shmouses** [comment]
Interesting information! Thanks a lot for such thoughtful comments! I believe Dr. Smith can shed more light on this.

**Comment by smiths** [comment]
@shmouses, the original comment from @muralidn is correct.  A requirement for a specific data format is a functional requirement.  @shmouses you are correct that the requirements are linked to the IMs, but they are not limited to that.  The requirements are less abstract than the IMs, because they are adding more details.  As we add more detail (become less abstract), it is natural for the number of items to become larger.  Every IM should trace to a requirement, but not every requirement has to trace to an IM.  :smile:

**Comment by shmouses** [comment]
As this requirement was not necessary for the software I removed it. 
Thus, issue is resolved: d61031a32be82f4fe56005dcbc4e67cd0e0ba523
