### ISSUE TITLE
Properties of correct soution

### ISSUE THREAD

**Issue by muralidn** [shmouses/SPDFEM#13]
@shmouses 

![image](https://user-images.githubusercontent.com/71282513/95973068-d46c0480-0e30-11eb-9647-49bf0bba40ff.png)

If I understand this correctly, you are saying that there is no single correct solution? 

In either case, the properties of a correct solution should be specific, or there should be a rationale explaining why/how the correct solution should be adjudged by the user.

**Comment by shmouses** [comment]
Hi Naveen, 
No, I am not saying there is no correct solution, what I say is that the system does not have an analytical solution for complex geometries. Therefore, knowledge of the user should judge if the result is rational or not. However, it is mentioned that the result can be compared with the analytical solution of the simple geometries.

**Comment by smiths** [comment]
@shmouses, the section for properties of a correct solution should list anything you know must be true of a correct solution.  The properties are not the same as calculating the correct results - that is covered by the requirements.  The properties section is for other properties.  A true solution must satisfy the property, but not all solutions that satisfy the property will be true solutions.  For instance, in some problems, the answers have to be positive.  Returning a negative number means the answer is wrong, but returning a positive number does not guarantee correctness.

Other properties for correct solutions might be a trend in the outputs based on a trend from the inputs.  For instance, if input x is increasing, then output y must be increasing.  This topic overlaps with the concept of metamorphic testing that we discussed in the VnV continued lecture.

Since the text of Section 4.2.7 is not a property, I will reopen this issue.  If you cannot find any properties, then you can write that as content for Section 4.2.7.

**Comment by shmouses** [comment]
Dear Dr. @smiths, I understand your point, I am actually changing my SRS while I am writing the VnV doc. I think after starting writing my VnV I got to understand the SRS document better but I didn't have this perspective before.

**Comment by smiths** [comment]
@shmouses, yes, great point.  Others in the class have made the same observation.  This is completely natural.  We cannot really have perfect knowledge when we are writing the SRS.  We learn by jumping in and starting the documentation.  As we get further in the project our understanding improves.

This is why we have two "official" iterations of the SRS in the course.  You should also have many sub-iterations as the term goes along.  Our aim is to fake a rational design process.  :smile:

**Comment by shmouses** [comment]
issue resolved: 7c16e5ced32e0282fe81dfb50d3d21f42b3cac55
